# Generated by Django 4.2.1 on 2023-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('balcony_num', models.IntegerField()),
                ('bedroom_num', models.IntegerField()),
                ('hall_num', models.IntegerField()),
                ('toilet_num', models.IntegerField()),
                ('facing', models.CharField(choices=[('e', '正东'), ('w', '正西'), ('n', '正北'), ('s', '正南'), ('ne', '东北'), ('nw', '西北'), ('se', '东南'), ('sw', '西南')], max_length=2)),
                ('floor', models.IntegerField()),
                ('floor_height', models.CharField(choices=[('l', '低'), ('m', '中'), ('h', '高')], max_length=1)),
                ('has_elevator', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renting_type', models.CharField(choices=[('整租', '整租'), ('合租', '合租')], max_length=2)),
                ('tags', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=30)),
                ('usage', models.CharField(choices=[('居家', '居家'), ('办公', '办公')], max_length=2)),
            ],
        ),
    ]
